require('configuration.client')
require('configuration.window')
require('configuration.tags')
require('configuration.screen')
require('configuration.keys')
require('configuration.mouse')
require('configuration.bling')
